import { ArcaneSigil } from './ArcaneSigil';

const NAMES = ['Business Central', 'Pistil', 'SingBox', 'Elemental Realms', 'smthgood', 'QuickFood'];
const CAPTIONS = ['Order from complexity.', 'Care, connected.', 'Invisible connections. Visible clarity.', 'A study in elemental wonder.', 'A more conscious kind of commerce.', 'Always in motion.'];

/** Stylized product studies, rather than screenshots of the production apps. */
export function ProjectArtwork({ index }: { index: number }) {
  return <div className={`project-study study-${index}`} aria-hidden="true">
    <span className="study-label">Project / 0{index + 1}</span>
    {index === 0 ? <div className="study-retail"><div className="study-screen"><div className="study-toolbar"><span>BC / Business Central</span><i /></div><div className="study-retail-layout"><div className="study-sidebar">Overview<br />Inventory<br />Orders<br />Reports</div><div><span className="study-tiny">TODAY AT A GLANCE</span><div className="study-metrics"><span>Sales<strong>24,580</strong></span><span>Orders<strong>128</strong></span></div><div className="study-bars">{[35, 55, 42, 74, 58, 89, 69, 100].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></div></div></div><div className="study-ticket">TRANSACTION COMPLETE<br /><strong>All in sync.</strong><span>|||| ||| || |||| |||</span></div></div>
    : index === 1 ? <div className="study-health"><div className="study-health-orbit" /><div className="study-phone"><span className="study-tiny">pistil ✳</span><h4>A little care.<br />A better day.</h4><div className="study-flower">✳</div><div className="study-phone-card">Your care, your way.<span>Find your specialist →</span></div></div><span className="study-health-note">Connected care.<br /><em>Human first.</em></span></div>
    : index === 2 ? <div className="study-network"><svg viewBox="0 0 480 210"><g fill="none" stroke="currentColor" strokeWidth=".8"><ellipse cx="240" cy="105" rx="190" ry="70" /><ellipse cx="240" cy="105" rx="100" ry="70" /><path d="M50 105h380M240 35v140M83 65h314M83 145h314" /><path d="m70 105 115-50 100 90 120-80" strokeWidth="2" /></g>{[[70,105],[185,55],[285,145],[405,65]].map(([x,y]) => <circle key={x} cx={x} cy={y} r="5" fill="currentColor" />)}</svg><div className="study-network-panel"><span>SingBox / Connected</span><strong>32 <small>ms</small></strong><span>Fast paths. Quiet complexity.</span></div></div>
    : index === 3 ? <div className="study-magic"><ArcaneSigil realm="fire" /><ArcaneSigil realm="water" /><ArcaneSigil realm="dark" /><span>IGNIS / AQUA / UMBRA</span></div>
    : index === 4 ? <div className="study-fashion"><div className="study-fashion-sheet"><span>smthgood.</span><div className="study-garment"><svg viewBox="0 0 120 130" fill="none" stroke="currentColor" strokeWidth="1.2"><path d="m42 18-25 13-12 31 20 9 9-16v61h52V55l9 16 20-9-12-31-25-13c-4 16-32 16-36 0Z" /><path d="M42 18c0 23 36 23 36 0M34 101h52" /></svg></div><strong>Wear your values.</strong><span>THE CONSCIOUS COLLECTION</span></div><div className="study-fashion-tag">Good things.<br /><em>Better choices.</em></div></div>
    : <div className="study-delivery"><svg viewBox="0 0 480 230" fill="none"><g stroke="currentColor" opacity=".22"><path d="m0 20 480 180M0 100l390 130M90 0l390 130M50 230 200-230m-80 230 200-230m-80 230 200-230" /></g><path d="m125 175 60-95 80 35 75-60" stroke="currentColor" strokeWidth="3" strokeDasharray="6 5" /><circle cx="125" cy="175" r="8" fill="currentColor" /><path d="M340 32c-17 0-25 12-25 25 0 18 25 39 25 39s25-21 25-39c0-13-8-25-25-25Z" stroke="currentColor" strokeWidth="2" /><circle cx="340" cy="57" r="7" stroke="currentColor" strokeWidth="2" /></svg><div className="study-delivery-label"><span>QuickFood</span><strong>On the way.</strong><span>Live tracking / Happier deliveries</span></div></div>}
    <span className="study-name">{NAMES[index]}</span><span className="study-caption">{CAPTIONS[index]}</span>
  </div>;
}
