import { ElementType } from '../types/index';
import { INITIAL_POPULATION_CONFIG } from './stickManPopulation';
import { STICK_MAN_ARCHETYPES } from '../data/stickManArchetypes';

export type DialogueType = 'ambient' | 'sitting' | 'duel' | 'prank' | 'flight' | 'float';

interface CharacterDialogueDeck {
  ambient: string[];
  sitting: string[];
  duel: string[];
  prank: string[];
  flight?: string[];
  float?: string[];
}

/**
 * VisitDialogueDeck:
 * Maintains individual, character-exclusive dialogue queues for all 28 stick men.
 * Dynamically populated by Google Gemini AI (/api/dialogue) once per visitor session.
 * Ensures zero line sharing between characters.
 */
class VisitDialogueDeck {
  private characterDecks: Map<string, CharacterDialogueDeck> = new Map();
  private hasFetchedAi = false;
  private isAiLoaded = false;
  private modelUsed: string = 'Gemini AI';

  constructor() {
    this.initDynamicBaselines();
  }

  /**
   * Initializes lightweight baseline placeholders from archetype attributes
   * before the Gemini AI script arrives over the network.
   */
  private initDynamicBaselines(): void {
    INITIAL_POPULATION_CONFIG.forEach((cfg) => {
      const def = STICK_MAN_ARCHETYPES[cfg.element] || STICK_MAN_ARCHETYPES.fire;
      this.characterDecks.set(cfg.id, {
        ambient: [`${def.symbol} ${def.name}: "${def.dialogueQuote}"`],
        sitting: [`${def.symbol} ${def.name} taking a breather on this ledge.`],
        duel: [`${def.symbol} ${def.name} preparing special move: ${def.specialMove}!`],
        prank: [`${def.symbol} Hey! Watch your step!`],
        flight: cfg.element === 'wind' ? [`🍃 ${def.name} soaring on the updraft!`] : undefined,
        float:
          cfg.element === 'space' ||
          cfg.element === 'void' ||
          cfg.element === 'light' ||
          cfg.element === 'time'
            ? [`${def.symbol} ${def.name} drifting in zero-gravity.`]
            : undefined,
      });
    });
  }

  /**
   * Initializes session: checks sessionStorage, otherwise calls Google Gemini AI
   * via /api/dialogue with action 'pregenerate_visit' to generate fresh script for all 28 characters.
   */
  public initSession(): void {
    if (typeof window === 'undefined' || this.hasFetchedAi) return;
    this.hasFetchedAi = true;

    // Check if already pre-generated in this browser session
    const cached = sessionStorage.getItem('stickman_visit_dialogue_deck');
    if (cached) {
      try {
        const parsed = JSON.parse(cached);
        this.applyAiScript(parsed.script || parsed);
        this.modelUsed = parsed.modelUsed || 'Gemini AI (Cached)';
        this.isAiLoaded = true;
        console.log(`✨ [Gemini AI] Loaded pre-generated visit dialogue deck from session cache.`);
        return;
      } catch {
        // Fall through to fetch fresh
      }
    }

    console.log(`✨ [Gemini AI] Pre-generating dialogue deck with Google Gemini...`);

    // Call API once for this visit
    fetch('/api/dialogue', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'pregenerate_visit' }),
    })
      .then((res) => res.json())
      .then((data) => {
        if (data.success && data.script) {
          sessionStorage.setItem(
            'stickman_visit_dialogue_deck',
            JSON.stringify({
              script: data.script,
              modelUsed: data.modelUsed,
            })
          );
          this.modelUsed = data.modelUsed || 'gemini-3.5-flash-lite';
          this.applyAiScript(data.script);
          this.isAiLoaded = true;
          console.log(`✨ [Gemini AI] Loaded dialogue script generated by ${this.modelUsed}!`);
        }
      })
      .catch((err) => {
        console.warn(`[Gemini AI] Offline or pre-generation failed, dynamic archetypes active.`, err);
      });
  }

  /**
   * Distributes Gemini AI-generated script across characters ensuring zero sharing
   */
  private applyAiScript(script: Record<string, Record<string, string[]>>): void {
    const elementCharMap: Record<string, string[]> = {};
    INITIAL_POPULATION_CONFIG.forEach((cfg) => {
      if (!elementCharMap[cfg.element]) elementCharMap[cfg.element] = [];
      elementCharMap[cfg.element].push(cfg.id);
    });

    Object.entries(script).forEach(([element, deck]) => {
      const chars = elementCharMap[element] || [];
      const char1 = chars[0];
      const char2 = chars[1];

      // Give Character 1 line 0 of each situation
      if (char1) {
        this.characterDecks.set(char1, {
          ambient: deck.ambient?.[0] ? [deck.ambient[0]] : [`✦ Guarding this digital realm.`],
          sitting: deck.sitting?.[0] ? [deck.sitting[0]] : [`🪑 Perched and watching.`],
          duel: deck.duel?.[0] ? [deck.duel[0]] : [`⚔️ Ready for a magic clash!`],
          prank: deck.prank?.[0] ? [deck.prank[0]] : [`😏 Sneak attack!`],
          flight: deck.flight?.[0] ? [deck.flight[0]] : undefined,
          float: deck.float?.[0] ? [deck.float[0]] : undefined,
        });
      }

      // Give Character 2 line 1 of each situation (completely distinct line)
      if (char2) {
        this.characterDecks.set(char2, {
          ambient: deck.ambient?.[1] ? [deck.ambient[1]] : [`✦ Standing sentinel over the district.`],
          sitting: deck.sitting?.[1] ? [deck.sitting[1]] : [`🪑 Surveying the architecture.`],
          duel: deck.duel?.[1] ? [deck.duel[1]] : [`⚔️ Defensive guard active!`],
          prank: deck.prank?.[1] ? [deck.prank[1]] : [`😏 Did you feel that?`],
          flight: deck.flight?.[1] ? [deck.flight[1]] : undefined,
          float: deck.float?.[1] ? [deck.float[1]] : undefined,
        });
      }
    });
  }

  /**
   * Retrieves a unique, non-shared line exclusively belonging to this character
   */
  public getCharacterDialogue(
    charId: string,
    type: DialogueType
  ): string {
    const deck = this.characterDecks.get(charId);
    if (!deck) {
      return '✦ Guarding this digital realm.';
    }

    const list = deck[type] as string[] | undefined;
    if (list && list.length > 0) {
      const line = list.shift()!;
      list.push(line);
      return line;
    }

    if (deck.ambient && deck.ambient.length > 0) {
      return deck.ambient[0];
    }

    return '✦ Standing sentinel over this district.';
  }

  public getModelUsed(): string {
    return this.modelUsed;
  }

  public getIsAiLoaded(): boolean {
    return this.isAiLoaded;
  }
}

export const visitDialogueDeck = new VisitDialogueDeck();
